name: Build Multi-Platform Executables

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pystray pillow
    
    - name: Build executable
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          python -m PyInstaller --onefile --windowed --name "英语学习助手" main.py
        elif [ "$RUNNER_OS" = "macOS" ]; then
          python -m PyInstaller build_mac.spec
        else
          python -m PyInstaller --onefile --name "英语学习助手" main.py
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: 英语学习助手-${{ runner.os }}
        path: dist/ 